name: Integration Tests
on:
  workflow_run:
    workflows:
      - Caller Integration Tests
    types:
      - completed
jobs:
  test_matrix:
    strategy:
      matrix:
        region: [ eu-west-1, us-east-1 ]
        include:
          - region: eu-west-1
            # secret names
            AWS_S3_BUCKET_NAME: AWS_S3_BUCKET_NAME
            AWS_SECURITY_GROUP_ID: AWS_SECURITY_GROUP_ID
            AWS_SUBNET_ID: AWS_SUBNET_ID
          - region: us-east-1
            # secret names
            AWS_S3_BUCKET_NAME: TEST_AWS_S3_BUCKET_NAME
            AWS_SECURITY_GROUP_ID: TEST_AWS_SECURITY_GROUP_ID
            AWS_SUBNET_ID: TEST_AWS_SUBNET_ID
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    env:
      PR_HEAD_SHA: 0
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: caller-integration-tests.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Read the pr_num file
        id: pr_num_reader
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: ./pr_number/pr_number

      - name: Get PR data
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          head_sha=$(gh api -H "Accept: application/vnd.github+json" /repos/spcaipers-arm/avhclient/pulls/${{ steps.pr_num_reader.outputs.content }} | jq .head.sha )
          echo "PR_HEAD_SHA=$head_sha" >> $GITHUB_ENV

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          ref: "${{ env.PR_HEAD_SHA }}"
          fetch-depth: 0

      - name: Checkout AVH-GetStarted example
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: AVH-GetStarted
          ref: main
          repository: ARM-software/AVH-GetStarted

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install AVH Client
        run: pip install .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::720528183931:role/Proj-vht-assume-role
          aws-region: ${{ matrix.region }}

      - name: Run tests
        id: avh
        env:
          AWS_DEFAULT_REGION: ${{ matrix.region }}
          AWS_S3_BUCKET_NAME: ${{ secrets[matrix.AWS_S3_BUCKET_NAME] }}
          AWS_SECURITY_GROUP_ID: ${{ secrets[matrix.AWS_SECURITY_GROUP_ID] }}
          AWS_SUBNET_ID: ${{ secrets[matrix.AWS_SUBNET_ID] }}
        run: |
          avhclient -b aws execute --specfile AVH-GetStarted/basic/avh.yml
